USE [master]
GO

CREATE DATABASE [TutorialDatabase]
GO

ALTER DATABASE [TutorialDatabase]SET COMPATIBILITY_LEVEL = 120
GO

ALTER DATABASE [TutorialDatabase]SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TutorialDatabase]SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TutorialDatabase]SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TutorialDatabase]SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TutorialDatabase]SET ARITHABORT OFF 
GO

ALTER DATABASE [TutorialDatabase]SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TutorialDatabase]SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TutorialDatabase]SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TutorialDatabase]SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TutorialDatabase]SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TutorialDatabase]SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TutorialDatabase]SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TutorialDatabase]SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TutorialDatabase]SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TutorialDatabase]SET  DISABLE_BROKER 
GO

ALTER DATABASE [TutorialDatabase]SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TutorialDatabase]SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TutorialDatabase]SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TutorialDatabase]SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TutorialDatabase]SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TutorialDatabase]SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TutorialDatabase]SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TutorialDatabase]SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TutorialDatabase]SET  MULTI_USER 
GO

ALTER DATABASE [TutorialDatabase]SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TutorialDatabase]SET DB_CHAINING OFF 
GO

ALTER DATABASE [TutorialDatabase]SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [abc] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [abc] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [abc] SET  READ_WRITE 
GO







